### ISSUE TITLE
Download fails with unsupported or outdated web browser

### ISSUE THREAD

**Issue by bullshit** [Dynatrace/Dynatrace-OneAgent-Ansible#27]
# Problem
*source* https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/blob/master/tasks/download.yml#L24-L36

The  ansible module  `get_url`  and `win_get_url` default http agent is `ansible-httpget` and can be configured with the `http_agent ` parameter
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-http_agent
https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_get_url_module.html#parameter-http_agent

The Dynatrace endpoint `/api/v1/deployment/installer/agent/unix/default/latest`  returns this and the ansible task which installs the agent fails.
````
$ tail -n 19 /tmp/Dynatrace-OneAgent-Linux-latest.sh
                <div class="container">
                        <div>
                                <div class="errorHeader">
                                        <div>This isn't a good fit</div>
                                </div>
                        </div>
                        <div class="detailsPanel">
                                You're using an unsupported or outdated web browser.<br />
                        </div>
                        <div class="links">
                                <a class="link"
                                   href="https://dt-url.net/op81plo?dt=s">
                                        List of supported browsers
                                </a>
                        </div>
                </div>
                <div class="illustration" name="client-server"><div class="inner"></div></div>
        </body>
</html>
````
````
TASK [dynatrace.oneagent : install dynatrace oneagent | linux] *********************************************************************************************************************************************************************************************************************

fatal: [xxxx]: FAILED! => {"changed": true, "cmd": ["sh", "/tmp/Dynatrace-OneAgent-Linux-latest.sh", "APP_LOG_CONTENT_ACCESS=1", "INFRA_ONLY=0"], "delta": "0:00:00.009544", "end": "2021-03-18 13:02:04.209622", "msg": "non-zero return code", "rc": 2, "start": "2021-03-18 13:02:04.200078", "stderr": "/tmp/Dynatrace-OneAgent-Linux-latest.sh: 12: Syntax error: newline unexpected", "stderr_lines": ["/tmp/Dynatrace-OneAgent-Linux-latest.sh: 12: Syntax error: newline unexpected"], "stdout": "", "stdout_lines": []}
````
# Possible solution 1
Set the http agent to an accepted browser
```
- name: download dynatrace oneagent | linux
  get_url:
    url: "{{ dynatrace_oneagent_installer_url }}"
    dest: "{{ dynatrace_oneagent_install_script }}"
    http_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
  when: ansible_system|lower == "linux" and not dynatrace_oneagent_state_file_linux.stat.exists

- name: download dynatrace OneAgent | windows
  win_get_url:
    url: "{{ dynatrace_oneagent_installer_url }}"
    dest: "{{ dynatrace_oneagent_install_script }}"
    http_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
  when: ansible_system|lower == "win32nt" and not dynatrace_oneagent_state_file_windows.stat.exists
```

# Possible solution 2
The Dynatrace endpoint `/api/v1/deployment/installer/agent/unix/default/latest` should support the browser user agent`ansible-httpget`.

# Improments
The Dynatrace endpoint `/api/v1/deployment/installer/agent/unix/default/latest` could use HTTP error codes instead of messages in html.
