### ISSUE TITLE
Playbook installs wrong arch

### ISSUE THREAD

**Issue by holms** [Dynatrace/Dynatrace-OneAgent-Ansible#9]
Here's my playbook

```
- hosts: swarm-prod
  remote_user: root
  gather_facts: False

  vars_files:
    - ./vars/prod.yml

  pre_tasks:
    - name: Bootstrap host with python 2.7
      raw: apt-get install -y python2.7 python-simplejson

  roles:
    - role: Dynatrace.OneAgent
      oneagent_installer_script_url: https://yni11271.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token={{ dynatrace_token }}&arch=x86&flavor=default
```

Here's outcome:

```
fatal: [206.189.xxx.xxx]: FAILED! => {"msg": "The conditional check 'ansible_architecture != \"armv7l\" and agent_installed.stat.exists == False' failed. The error was: error while evaluating conditional (ansible_architecture != \"armv7l\" and agent_installed.stat.exists == False): 'ansible_architecture' is undefined\n\nThe error appears to have been in '/home/holms/.ansible/roles/Dynatrace.OneAgent/tasks/main.yml': line 41, column 4, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n - name: \"Install Dynatrace OneAgent\"\n   ^ here\n"}
```

Ansible version:

```
holms@debian ~/D/c/l/a/prod> ansible --version
ansible 2.5.4
  config file = None
  configured module search path = [u'/home/holms/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

How did we end up with selecting arm ach? :) As you can see it's specified in URL as x86
